### ISSUE TITLE
Port travis-ci over to ansible-mig

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#212]
@juju4 has been working on https://github.com/juju4/ansible-mig and we should use this in continuous integration, instead of the standalone installation script.

**Comment by juju4** [comment]
Hello

Just to explain, most tests are done with serverspec (ruby)
https://github.com/juju4/ansible-mig/tree/master/test/integration/default/serverspec
and what is possible is described here
http://serverspec.org/resource_types.html

Please note serverspec v2 has just been released and might change a lot (or not). didn't dig it

I tried to use also serverspec at the end of travis/gce but it falls in error most probably because of different environment vs kitchen/vagrant/virtualbox

at this point, the ansible role is up and rolling except connection between server and localhost agent.
Ideally after, it would be nice to be able to have some full cli to do some non-interactive test to validate main mig functions or the API call.
