### ISSUE TITLE
console messages (500,000 of them) 

### ISSUE THREAD

**Issue by Phrozyn** [mozilla/mig#278]
Getting a bazillion of these messages (looks like my console has a limit of 500k messages.)
Looking at ps auxwww output, it appears the process is generally sleeping. So it doesn't seem to be causing any issues other than this message being repeated. So i can't say when this started except maybe when I upgraded to Sierra on the 16th.

**/kernel  (/System/Library/Extensions/AppleMobileFileIntegrity,kext/Contents/MacOS/AppleMobileFileIntegrity)**
- default   15:37:16.296978 -0500   kernel  AMFI: allowing exception handler for 'mig-agent' (708) because the process is unsigned.
- default   15:37:16.297053 -0500   kernel  AMFI: allowing exception handler for 'mig-agent' (708) because the process is unsigned.

**ps output:**
- 10114  mig-agent    0.0       00:00.00 5      0    24    1316K  0B     0B     10109 10109 sleeping *0[1]             0.00000 0.00000    0    1148        73      29          14
- 10109  mig-loader   0.0       00:00.28 7      1    50    10M    0B     0B     10109 1     sleeping *0[1]             0.00000 0.00000    0    5940        215     148         50

**Comment by ameihm0912** [comment]
It looks like with Sierra the binaries will now need to be signed, in addition to the installer which is already signed.

codesign on the current agent build appears to cause some issues as are described in https://github.com/golang/go/issues/11887 due to the presence of CGO for the memory module. I'll take a look at it in more detail.
