### ISSUE TITLE
Document API create action signing process

### ISSUE THREAD

**Issue by nick-allen** [mozilla/mig#311]
The documentation for action create API endpoint (http://mig.mozilla.org/doc/api.rst.html#post-api-v1-action-create) does not describe how to sign an action, making it impossible to create custom clients not leveraging mig codebase. 

API appears to be expecting signature of string representation of action (https://github.com/mozilla/mig/blob/master/action.go#L298), but documentation similar to what is provided for procedure to generate API authentication token (http://mig.mozilla.org/doc/api.rst.html#authentication-with-x-pgpauthorization-version-1) would be useful when creating new clients.

**Comment by jvehent** [comment]
Action signature is a simple PGP signature computed on a stringified action: https://github.com/mozilla/mig/blob/master/action.go#L329-L338

The problem here is we don't canonicalize the json of the action when signing/verifying, so for the algorithm to succeed, both signing and verifier must use the same json library. Otherwise keys would be in a different order. There are various algorithms that can be used to canonicalize JSON, but at the time,having no plan to write a client in a different language, that seemed unnecessary.

We already decided to break backward compatibility with 1.0, so the logic could be changed for that release, but if you want to write a client that works with current agents, you'll need to reimplement the way Go marshal/unmarshals JSON to sign actions.

**Comment by ameihm0912** [comment]
Looks like this was documented in b70319d
