### ISSUE TITLE
Improve distribution discovery for linux agent builds

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/mig#326]
In some cases inaccurate data is returned, and some functions such as findOSInfo() return error messages (e.g., calling getLSBRelease()) which can generate errors which are not fatal. It would be good to revisit ensuring the distribution information returned in this part of the code is accurate and clean up any errors that are not required to be reported.

**Comment by ameihm0912** [comment]
@floatingatoll fyi

**Comment by floatingatoll** [comment]
In this case, my thoughts (sequentially) as the end-user when I encountered the [info]-level message about getLSBRelease were:

1. Do I need to install lsb_release to gain full mig functionality?
2. Are we exposed to risk due to missing data from lsb_release?
3. If neither of those is true, why is the warning enabled in non-debug deployments?
