### ISSUE TITLE
Ownership Transfer

### ISSUE THREAD

**Issue by mbhatt1** [mozilla/mig#496]
Hi, 

Project looks super cool! I can take ownership if this project is going to die otherwise. 

Could you also tell me which is the last set of operating systems this was tested on? 

Thank you!

**Comment by tristanweir** [comment]
Hi, thanks for your enthusiasm! 

After some internal discussion, we have decided to Archive and read only this repo instead of transferring ownership. We will do so in the next few days. However, if you want to work on it, please feel free to fork it and continue development.

This was last used in production on CentOS 7.
